import './index.html';
import './style/index.scss';
import './modules/types-item';
import './modules/cases-item';
import './modules/scrolling-parallax';
import AOS from 'aos';
AOS.init();
import './modules/validation';
// import './modules/cookies';
import {Fancybox} from "@fancyapps/ui";